### ISSUE TITLE
DrivingAssertions: wrong sortorder in DataGrid

### ISSUE THREAD

**Issue by Martin-Jonasse** [hertus/sfitixi#114]
The sort order for Driving Assertions in the DataGrid is fine for lists with less than 15 rows. After that sorting is very strange (based upon the DrivingAssertion.id).

![issue114](https://cloud.githubusercontent.com/assets/4991526/6075100/35fd9b08-adcc-11e4-8044-2607ca68f669.PNG)

Expectations: 
1) DataGrid rows are ordered ascending, by date and shift(start time).
2) Rows with isDeleted=true or date and shift.start in the past tense are not displayed.

**Comment by Josi-Conrad** [comment]
Lieber Martin

Sogar in den Ferien kannst du es nicht lassen.

Nun stimmt die Reihenfolge ­ super!

Ich werde auch noch den Laptop holen bevor wir nach Obersaxen fahren, damit
ich weitermachen kann an der Hilfe Dokumentation.

Wir freuen uns natürlich sehr auf euch, das Engadin und gemütliche Momente
mit euch.

Sicher werden wir noch telefonieren und Details abmachen.

Bis bald und liebe Grüsse

Josi & Silvia
_________________
J. & S. Conrad
Hofstrasse 9
CH-6300 Zug
Privat   +41-41 710 17 10
sijoco@datazug.ch



Von:  Martin Jonasse <notifications@github.com>
Antworten an:  hertus/sfitixi
<reply+0072a508d0eb746638eaf9a2fb04cfd540b7ce6647f3c07392cf0000000110ec14459
2a169ce036246c2@reply.github.com>
Datum:  Thu, 05 Feb 2015 21:33:57 -0800
An:  hertus/sfitixi <sfitixi@noreply.github.com>
Betreff:  [sfitixi] DrivingAssertions: wrong sortorder in DataGrid (#114)


The sort order for Driving Assertions in the DataGrid is fine for lists with
less than 15 rows. After that sorting is very strange (based upon the
DrivingAssertion.id).

‹
Reply to this email directly or view it on GitHub
<https://github.com/hertus/sfitixi/issues/114> .

**Comment by Martin-Jonasse** [comment]
Fixed issue by adding field sortOrder = Date(WorkingDate) + Time(ShiftType) and using this field for sorting the assertions. This is indeed redundant, however sorting derived fields is not possible in DataGrids, so really we have no choice.
