### ISSUE TITLE
Fahrer -> Neuer Fahrer -> Geschlecht

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#115]
"Neuer Fahrer" erfassen
ebenso bei
"Neuer Vormund"
Problem: Keine Fehlermeldung, wenn Geschlecht nicht ausgewählt wird!

Erwartet wird:
Fehlermeldung wenn "Mussfeld" nicht ausgefüllt wird z.B. Radio Button wird rot 
oder 
Default Einstellung ist "männlich"  -->  siehe "Fahrgast -> Neuer Fahrgast" dort ist es richtig!

**Comment by Martin-Jonasse** [comment]
Fixed the field PersonType.gender to have the default 'm' (masculin), sorry ladies.
