### ISSUE TITLE
Fehler-Meldung "Neuer Einsatzplan"

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#129]
Fehlermeldung bei Einsatzplan erfassen (siehe Snapshot)

![einsatzplan](https://cloud.githubusercontent.com/assets/7513352/8203364/900b26fc-14e1-11e5-9b8d-600421b24986.PNG)

**Comment by Martin-Jonasse** [comment]
Guten morgen Josi

Diese Fehlermeldung „Mehrfachbelegung …“ erscheint dann, wenn ein Einsatzplan Schichten betrifft die bereits anderswo eingeplant sind. D.h. in ein anderen Einsatzplan oder in ein Einsatz, hier Dienstag Schicht 1.

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10

Am 17.06.2015 um 11:11 schrieb Josi Conrad <notifications@github.com>:

**Comment by Josi-Conrad** [comment]
Danke Martin für deine Antwort.

Während dem ich Snapshots für die Doku gemacht habe, hatte ich den Eindruck,
dass nicht alles koscher war.

Gerne würde ich alles einmal mit dir anschauen, dann wird’s für mich sicher
klarer.

Weiter hätte ich noch ein paar Fragen bezgl. Roadmap. Eventuell könnten wir
uns am Montag-Vormittag deswegen kurz treffen, so ca. für eine halbe Stunde
– was meinst du?

Ich muss mit Silvia nach Bad Ragaz an’s Klassentreffen und bin eventuell
schon am Samstag wieder zurück.

Gruss Josi
_________________
J. & S. Conrad
Hofstrasse 9
CH-6300 Zug
Privat   +41-41 710 17 10
sijoco@datazug.ch



Von:  Martin Jonasse <notifications@github.com>
Antworten an:  hertus/sfitixi
<reply+0072a508be9ec679060c1f4000a80445e3a860515f436a5c92cf00000001119a2d179
2a169ce054d7961@reply.github.com>
Datum:  Wed, 17 Jun 2015 23:54:15 -0700
An:  hertus/sfitixi <sfitixi@noreply.github.com>
Cc:  Josy Conrad <sijoco@datazug.ch>
Betreff:  Re: [sfitixi] Fehler-Meldung "Neuer Einsatzplan" (#129)

Guten morgen Josi

Diese Fehlermeldung „Mehrfachbelegung …“ erscheint dann, wenn ein
Einsatzplan Schichten betrifft die bereits anderswo eingeplant sind. D.h. in
ein anderen Einsatzplan oder in ein Einsatz, hier Dienstag Schicht 1.

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10

Am 17.06.2015 um 11:11 schrieb Josi Conrad <notifications@github.com>:

> Fehlermeldung bei Einsatzplan erfassen (siehe Snapshot)
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 


—
Reply to this email directly or view it on GitHub
<https://github.com/hertus/sfitixi/issues/129#issuecomment-113055733> .

**Comment by Martin-Jonasse** [comment]
Hoi Josi

Wir treffen uns Montag 14:00 bei Tixizug, ist das für Dich OK?
Ich wünsche Dir und Silvia ein schönes Wochenende.

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10

Am 19.06.2015 um 06:19 schrieb Josi Conrad <notifications@github.com>:

**Comment by Josi-Conrad** [comment]
Guten Morgen Martin

Am Montag um 14:00 Uhr haben wir die Vorstandssitzung.

Wir treffen uns oder telefonieren am Montag Vormittag was meinst du?

Gruss Josi
_________________
J. & S. Conrad
Hofstrasse 9
CH-6300 Zug
Privat   +41-41 710 17 10
sijoco@datazug.ch



Von:  Martin Jonasse <notifications@github.com>
Antworten an:  hertus/sfitixi
<reply+0072a508bb5fe9fbbce212adc92d2dda2d2a35e723fb4dde92cf00000001119c34899
2a169ce054d7961@reply.github.com>
Datum:  Fri, 19 Jun 2015 12:50:33 -0700
An:  hertus/sfitixi <sfitixi@noreply.github.com>
Cc:  Josy Conrad <sijoco@datazug.ch>
Betreff:  Re: [sfitixi] Fehler-Meldung "Neuer Einsatzplan" (#129)

Hoi Josi

Wir treffen uns Montag 14:00 bei Tixizug, ist das für Dich OK?
Ich wünsche Dir und Silvia ein schönes Wochenende.

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10

Am 19.06.2015 um 06:19 schrieb Josi Conrad <notifications@github.com>:

> Danke Martin für deine Antwort.
> 
> Während dem ich Snapshots für die Doku gemacht habe, hatte ich den Eindruck,
> dass nicht alles koscher war.
> 
> Gerne würde ich alles einmal mit dir anschauen, dann wird’s für mich sicher
> klarer.
> 
> Weiter hätte ich noch ein paar Fragen bezgl. Roadmap. Eventuell könnten wir
> uns am Montag-Vormittag deswegen kurz treffen, so ca. für eine halbe Stunde
> – was meinst du?
> 
> Ich muss mit Silvia nach Bad Ragaz an’s Klassentreffen und bin eventuell
> schon am Samstag wieder zurück.
> 
> Gruss Josi
> _________________
> J. & S. Conrad
> Hofstrasse 9
> CH-6300 Zug
> Privat +41-41 710 17 10
> sijoco@datazug.ch
> 
> 
> 
> Von: Martin Jonasse <notifications@github.com>
> Antworten an: hertus/sfitixi
> <reply+0072a508be9ec679060c1f4000a80445e3a860515f436a5c92cf00000001119a2d179
> 2a169ce054d7961@reply.github.com>
> Datum: Wed, 17 Jun 2015 23:54:15 -0700
> An: hertus/sfitixi <sfitixi@noreply.github.com>
> Cc: Josy Conrad <sijoco@datazug.ch>
> Betreff: Re: [sfitixi] Fehler-Meldung "Neuer Einsatzplan" (#129)
> 
> Guten morgen Josi
> 
> Diese Fehlermeldung „Mehrfachbelegung …“ erscheint dann, wenn ein
> Einsatzplan Schichten betrifft die bereits anderswo eingeplant sind. D.h. in
> ein anderen Einsatzplan oder in ein Einsatz, hier Dienstag Schicht 1.
> 
> LbG Martin
> 
> Martin Jonasse
> Seemattstrasse 38
> 6333 Hünenberg See
> Privat: 041 780 76 12
> Mobile: 079 832 69 10
> 
> Am 17.06.2015 um 11:11 schrieb Josi Conrad <notifications@github.com>:
> 
> > Fehlermeldung bei Einsatzplan erfassen (siehe Snapshot)
> > 
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> 
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hertus/sfitixi/issues/129#issuecomment-113055733> .
> 
> 
> 
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 


—
Reply to this email directly or view it on GitHub
<https://github.com/hertus/sfitixi/issues/129#issuecomment-113623367> .

**Comment by Martin-Jonasse** [comment]
This is a feature, not a bug. Please read the error message (second line).

**Comment by Martin-Jonasse** [comment]
Close.
