### ISSUE TITLE
Fatal exception in DrivingOrder

### ISSUE THREAD

**Issue by Martin-Jonasse** [hertus/sfitixi#138]
![crash driving order](https://cloud.githubusercontent.com/assets/4991526/10758932/be805530-7cb4-11e5-8dce-aef3ee81068c.PNG)

**Comment by Martin-Jonasse** [comment]
![doctrine mix up](https://cloud.githubusercontent.com/assets/4991526/10762914/31ddba1e-7cc8-11e5-9fb3-0fb1171481ae.PNG)
Doctrine put the driving orders "on top", instead of the driving missions.

Cause: verschlimmbesserungohnetestenduidiot

**Comment by Josi-Conrad** [comment]
verschlimmbesserungohnetestenduidiot

Was genau heisst das ? Hat das so etwa mit Selbsterkenntnis. Tönt auf
jeden Fall super!!!

Danke und Gruss

Josi
_________________
J. & S. Conrad
Hofstrasse 9
CH-6300 Zug
Privat   +41-41 710 17 10
sijoco@datazug.ch



Von:  Martin Jonasse <notifications@github.com>
Antworten an:  hertus/sfitixi
<reply+0072a508532f09470e32c7e7fcb9603f9e5f39c099ff3a5892cf0000000112475b679
2a169ce06c519a6@reply.github.com>
Datum:  Tue, 27 Oct 2015 08:33:59 -0700
An:  hertus/sfitixi <sfitixi@noreply.github.com>
Betreff:  Re: [sfitixi] Fatal exception in DrivingOrder (#138)


Closed #138 <https://github.com/hertus/sfitixi/issues/138> .


Reply to this email directly or view it on GitHub
<https://github.com/hertus/sfitixi/issues/138#event-446924830> .

**Comment by Martin-Jonasse** [comment]
selbsterkenntnis!

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 27.10.2015 um 18:08 schrieb Josi Conrad <notifications@github.com>:
