### ISSUE TITLE
Fehler - Neuer Einsatzplan (Hanspeter Muster)

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#143]
Fehler bei "Erfassen neuer Einsatzplan"!

![fehler neuer einsatzplan](https://cloud.githubusercontent.com/assets/7513352/11896201/c3e21bb4-a584-11e5-942e-eecb962401e0.PNG)

**Comment by Martin-Jonasse** [comment]
Fixed this by trimming the error message in the "check for error message".

**Comment by Martin-Jonasse** [comment]
Fixed.
