### ISSUE TITLE
Fehler Fahraufträge

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#144]
Fahrauftrag neu -> manuell bearbeiten -> 
![fehler fahrauftrage](https://cloud.githubusercontent.com/assets/7513352/11898663/c9eca190-a599-11e5-82b6-fabf8d6236d3.PNG)
Fahrauftrag gelöscht -> nochmals Fahrauftrag neu gleiches Datum -> Tagesplan auswählen ->Tagesplan optimieren -> Bereitstellen -> Anzeigen -> gleiche Fehlermeldung!

**Comment by Martin-Jonasse** [comment]
Fixed this today.
Commit https://github.com/hertus/sfitixi/commit/a3720e01d062ed6ccdae0d8d7d4c1efa0cc3fae9
