### ISSUE TITLE
Fehlermeldung Browser

### ISSUE THREAD

**Issue by ruemon** [hertus/sfitixi#145]
![browser](https://cloud.githubusercontent.com/assets/16398634/11951514/aff5882e-a891-11e5-8e01-93d218c28200.png)

'Internet Explorer' wird nicht unterstützt, resp. es können Fehler auftreten. Was bedeutet dies für uns? Auch im Zusammenhang mit MS Office Programmen?

**Comment by Martin-Jonasse** [comment]
Wir unterstützen zwei Browser: FireFox ind Chrome. D.h. die GUI (Benutzer-Schnittstelle) der Applikation zeigt richtig an (screen design).

Bei alle anderen Browser wie Internet Explorer, Opera, Safari, Netscapre Navigator, Vivaldi etc. kann es zu Abweichungen in der Darstellung kommen, weil HTML5 / CSS3 Standards nur unzureichend von den Browser unterstützt werden. 

Für den Benutzer bedeutet dies folgendes, 
1. Wenn ein andere Browser als FireFox oder Chrom oder Safari verwendet wird.
2. Wird die Fehlermeldung (siehe oben) immer bei öffnen des Home-Pages dargestellt.
3. Die Applikation funktioniert wie geplant, kann aber in der Benutzer GUI falsch anzeigen.
4. Solche Abweichungen(3) werden nicht "geflickt", auch wenn Sie als Fehler gemeldet werden.

Es ist wie bei ein Renault Garage, dort werden meist keine Mercedes geflickt.

**Comment by Martin-Jonasse** [comment]
SHA-1: 31b8f5c22b4afa2a2b8bb390891a065ec1aaf1b0
* Added cookie for browser name (valid 12 hours). If the browser name is not Firefox, Chrome, Safari an error message will be displayed max. once every 12 hours.
