### ISSUE TITLE
Servicepläne: Im Tagesplan wird ganzer Tag blockiert

### ISSUE THREAD

**Issue by ruemon** [hertus/sfitixi#147]
Es wird ein Servicplan erfasst z.B. 14.1.2016 07:00 - 12:00. Im Tagesplan wird das entsprechende Fahrzeug den ganzen Tag mit einem blauen Balken abblockiert.

**Comment by Martin-Jonasse** [comment]
This is not a bug it's a feature: F50
![servcieplan](https://cloud.githubusercontent.com/assets/4991526/12259189/3f255758-b914-11e5-9b23-2e6d3bbda698.PNG)

![servcieplan2](https://cloud.githubusercontent.com/assets/4991526/12259194/44664560-b914-11e5-9a76-2094f1c7799f.PNG)

**Comment by ruemon** [comment]
Wenn ich eine zeitliche Begrenzung für den Serviceplan eingeben kann, warum wird dann der ganze Tag abblockiert?
Gruss Monika

**Comment by Josi-Conrad** [comment]
Liebe Monika
Ich fahre jetzt von Obersaxen ab und bin je nach Verkehr gegen 10:00 Uhr in der Zentrale.
Und erstens kommt es anders,
Und zweitens als man denkt!

Liebe Grüsse
Josi

Von meinem iPad gesendet
