### ISSUE TITLE
Fahrgast editieren -> editieren -> Fehler!

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#151]
Fahrer -> editieren -> falsches Geschlecht!
erwartet wird, dass bei weiblichem Fahrgast schwarzer Punkt bei weiblich steht.
![martulla](https://cloud.githubusercontent.com/assets/7513352/12323072/d101b6f8-bab8-11e5-8458-79e54cba8350.PNG)
![martulla-2](https://cloud.githubusercontent.com/assets/7513352/12323073/d10441e8-bab8-11e5-9469-1999e49ff971.PNG)
![martulla-3](https://cloud.githubusercontent.com/assets/7513352/12323074/d105a54c-bab8-11e5-84ff-49b4fbc4d57f.PNG)

**Comment by Martin-Jonasse** [comment]
Guten morgen Josi

Erst einmal handelt es sich um zwei unterschiedliche Felder:

1. Geschlecht: männlich oder weiblich (nur ein einzige Wert ist möglich)
2. Anrede: Frau, Herr, Dr. med., Schwester, Hochwürden etc. (beliebige Werte sind möglich)

Die beide Felder sind nicht verknüpft, die Software prüft keine Zusammenhänge. Daher kann es sich nicht um ein Fehler handeln.


Vielleicht erwartest Du, dass die Software offensichtlich „falsche“ Kombinationen signalisiert / moniert:

Fehler1: Geschlecht=männlich, Anrede=Frau
Fehler2: Geschlecht=weiblich, Anrede=Herr
Fehler3: ?

Allerdings ist zu bedenken, dass in unsere Zeit durchaus Fälle gibt wo Fehler1 und Fehler2 keine Fehler sind (Transvestiten).
Ich bitte Dir deine Meldung zu überdenken und auszuformulieren.

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 14.01.2016 um 12:18 schrieb Josi Conrad <notifications@github.com>:

**Comment by ruemon** [comment]
Hoi Martin 
Es geht hier eigentlich darum, dass bei jedem "Editieren" ein Default-Wert "männlich" gesetzt wird. Das heisst aus "männlein" wird "weiblein" :-) 
Lieber Gruss
Monika

**Comment by Martin-Jonasse** [comment]
Guten Abend Monika

Gehe ich recht in der Annahme das es dann passiert wenn bereits ein „weibliche“ Fahrgast gespeichert wurde und 
beim nächsten Editieren wird das Attribute „männlich“ gesetzt?

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 19.01.2016 um 16:03 schrieb ruemon <notifications@github.com>:

**Comment by ruemon** [comment]
Hoi Martin 

Ja, genau. Ich habe das auf der Fahrer-Seite beobachtet. Ich lege eine Fahrerin (weiblich) an und wenn ich mit editieren rein gehe, gibt eine „Geschlechtsumwandlung“. :)

Lieber Gruss

Monika

 

Freundliche Grüsse

 

TIXI ZUG

 

Monika Rüegg

Leiterin Zentrale / Stv. Geschäftsführerin

 

General-Guisan-Str. 22

6300 Zug

Tel  041 711 84 84

Fax 041 711 84 59

 <mailto:monika.rueegg@tixizug.ch> monika.rueegg@tixizug.ch

 <http://www.tixizug.ch> http://www.tixizug.ch

 

Von: Martin Jonasse [mailto:notifications@github.com] 
Gesendet: Dienstag, 19. Januar 2016 18:31
An: hertus/sfitixi <sfitixi@noreply.github.com>
Cc: ruemon <monika.rueegg@tixizug.ch>
Betreff: Re: [sfitixi] Fahrgast editieren -> editieren -> Fehler! (#151)

 

Guten Abend Monika

Gehe ich recht in der Annahme das es dann passiert wenn bereits ein „weibliche“ Fahrgast gespeichert wurde und 
beim nächsten Editieren wird das Attribute „männlich“ gesetzt?

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat: 041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 19.01.2016 um 16:03 schrieb ruemon <notifications@github.com <mailto:notifications@github.com> >:

**Comment by Martin-Jonasse** [comment]
Monika

Dann ist es eine Fehler. Um das festzustellen und dokumentieren (Entwickler können keine Gedanken lesen und sind erst noch vergesslich) habe ich einen Link unten in der iTIXI-Webseite angebracht:


Wenn Du auf „Fehlerbericht" klickst, dann öffnet sich ein Email mit eine vorbereitete Text. Die Fragezeichen (?) geben an wo Informationen betreffend den Fehler eingegeben werden müssen. Dies soll verhindern, das endlose emails hin und her geschickt werden zwischen der Fehler-Erkenner und der Entwickler. 
Später habt ihr ein Supporten, der kostet Euch dann ca. CHF 125.- pro Stunden (ich bin dann „in Pension“) darum ist es in Euren Interesse schnell zu ein Resultat zu kommen.


Betreffend issue#151 heisst es:

Fahrer -> editieren -> falsches Geschlecht!
erwartet wird, dass bei weiblichem Fahrgast schwarzer Punkt bei weiblich steht.

sollte heissen
Fahrer -> editieren -> Geschlecht wird als weiblich angelegt, etc. -> Speichern
später der gleiche Fahrer -> editieren -> nun wird das Geschlecht als männlich dargestellt
erwartet wird, dass bei weiblichem Fahrgast schwarzer Punkt bei weiblich steht.

Hieraus lernen wir, dass der Ablauf (Reihenfolge der Eingaben) für die Dokumentation einer Fehler enorm wichtig ist.

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 20.01.2016 um 13:20 schrieb ruemon <notifications@github.com>:

**Comment by ruemon** [comment]
Hoi Martin

 

Danke für die Instruktion betreffend Fehlerhandling. Ich werde das künftig so machen.

 

Lieber Gruss

Martin

 

 

Von: Martin Jonasse [mailto:notifications@github.com] 
Gesendet: Donnerstag, 21. Januar 2016 17:41
An: hertus/sfitixi <sfitixi@noreply.github.com>
Cc: ruemon <monika.rueegg@tixizug.ch>
Betreff: Re: [sfitixi] Fahrgast editieren -> editieren -> Fehler! (#151)

 

Monika

Dann ist es eine Fehler. Um das festzustellen und dokumentieren (Entwickler können keine Gedanken lesen und sind erst noch vergesslich) habe ich einen Link unten in der iTIXI-Webseite angebracht:


Wenn Du auf „Fehlerbericht" klickst, dann öffnet sich ein Email mit eine vorbereitete Text. Die Fragezeichen (?) geben an wo Informationen betreffend den Fehler eingegeben werden müssen. Dies soll verhindern, das endlose emails hin und her geschickt werden zwischen der Fehler-Erkenner und der Entwickler. 
Später habt ihr ein Supporten, der kostet Euch dann ca. CHF 125.- pro Stunden (ich bin dann „in Pension“) darum ist es in Euren Interesse schnell zu ein Resultat zu kommen.


Betreffend issue#151 heisst es:

Fahrer -> editieren -> falsches Geschlecht!
erwartet wird, dass bei weiblichem Fahrgast schwarzer Punkt bei weiblich steht.

sollte heissen
Fahrer -> editieren -> Geschlecht wird als weiblich angelegt, etc. -> Speichern
später der gleiche Fahrer -> editieren -> nun wird das Geschlecht als männlich dargestellt
erwartet wird, dass bei weiblichem Fahrgast schwarzer Punkt bei weiblich steht.

Hieraus lernen wir, dass der Ablauf (Reihenfolge der Eingaben) für die Dokumentation einer Fehler enorm wichtig ist.

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat: 041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 20.01.2016 um 13:20 schrieb ruemon <notifications@github.com <mailto:notifications@github.com> >:

**Comment by Martin-Jonasse** [comment]
Found error in PersonType.php, remove line with 'data' => 'm',:
![persontypeerror](https://cloud.githubusercontent.com/assets/4991526/13310604/cd0bdbce-db87-11e5-8007-05d252b7bba2.PNG)

**Comment by Josi-Conrad** [comment]
Lieber Martin
Das ist ja unglaublich - heute um 06:22 - brauchst du keinen Schlaf, oder ist das Bett im Engadin so schlecht, oder hast du heute keine Lust zum Skifahren?
Du legst ja einen richtigen Endspurt hin und so werde ich ab Montag richtig viel zu tun haben.
Apropo Montag - kann ich dich am Montagvormittag für ca eine Stunde treffen, damit ich den neusten Stand abholen kann, denn ich sollte am Nachmittag den Vortsand informieren.
Nächste Woche bin ich wieder in Zug und werde Versäumtes nachholen.
Geniess das Engadin und liebe Grüsse an Wicky's und Rosmarie.
Josi & Silva


Von meinem iPad gesendet

**Comment by Martin-Jonasse** [comment]
Fixed issue, the gender-property is persisted correctly:
![mannlichweiblich](https://cloud.githubusercontent.com/assets/4991526/13378490/bab79980-de08-11e5-9f5b-11c9e2fdfcda.PNG)

This has been successfully tested in passengers, drivers and custodians.
