### ISSUE TITLE
Fahrauftrag ausdrucken -> Fehler!

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#152]
Fahrauftrag kann wohl angezeigt, jedoch nicht mehr ausgedruckt werden!
![print-fahrauftrag](https://cloud.githubusercontent.com/assets/7513352/12327459/f9ab19c8-bad6-11e5-81e8-c89a0dfa1117.PNG)

**Comment by Josi-Conrad** [comment]
Fahrauftrag kann wohl angezeigt, jedoch nicht mehr ausgedruckt werden!

**Comment by Martin-Jonasse** [comment]
Guten morgen Josi

Ist kein Fehler, es ist noch nicht implementiert.

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 14.01.2016 um 15:56 schrieb Josi Conrad <notifications@github.com>:
