### ISSUE TITLE
Fahrauftrag ausdrucken -> Fehler!

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#153]
Erwartet wird:
Bereitstellen -> Fahrauftrag -> Drucken
Fahrauftrag wird auf Printer gedruckt!
Ausgegeben wird:
![print-fahrauftrag](https://cloud.githubusercontent.com/assets/7513352/12327845/e9ce9a6e-bad8-11e5-8696-bd9ab441e274.PNG)

**Comment by Martin-Jonasse** [comment]
Guten morgen Josi

Ist kein Fehler, nur ein undeutliche Fehlermeldung. Diese Funktion ist noch nicht implementiert. 

Ich bin seit letzten Freitag genau hier am bauen, bald sollte Bereitstellen->Fahrauftrag->Drucken auch möglich sein.

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 14.01.2016 um 16:08 schrieb Josi Conrad <notifications@github.com>:

**Comment by Martin-Jonasse** [comment]
This is "work in progress".

**Comment by Martin-Jonasse** [comment]
Implementiert: Fahrauftrag -> Drucken erstellt eine PDF Datei für den Download bereit, gedruckt wird in Adobe Acrobat Reader.
![fahrauftrag](https://cloud.githubusercontent.com/assets/4991526/13311372/4f8101c8-db8e-11e5-9314-586fc5d48bd6.PNG)
