### ISSUE TITLE
Fahrer mutieren zu kein Rollstuhl 

### ISSUE THREAD

**Issue by ruemon** [hertus/sfitixi#154]
Hoi Martin

Folgender issue: Ein Fahrer meldet er kann ab sofort keine Rollstuhlfahrten mehr machen. Ich deaktiviere die Checkbox Rollstuhl in den Fahrerdetails. Für bereits angelegte Einsätze, resp. Monats-/Tagespläne gibt es keine Warnung für die Zuteilung von Rollstuhlfahrten (auch wenn ich auf "Fahrten optimieren" klicke). Gibt es eine Möglichkeit einer Warnung?
Glg Monika
![fahrer](https://cloud.githubusercontent.com/assets/16398634/12422769/c77e5186-bec8-11e5-9c77-223f64126c74.png)
![adr](https://cloud.githubusercontent.com/assets/16398634/12422772/cd144dda-bec8-11e5-98f6-b232d595fe31.png)
![tages](https://cloud.githubusercontent.com/assets/16398634/12422774/cee38f36-bec8-11e5-8cf1-f430e1c319ea.png)

**Comment by Martin-Jonasse** [comment]
Guten Abend Monika

Ist ein bekannter Fehler. So etwas sollte durch „Fahrten optimieren“ behoben werden, tut es aber nicht. 

Siehe auch Issue#149.

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 19.01.2016 um 16:23 schrieb ruemon <notifications@github.com>:

**Comment by Martin-Jonasse** [comment]
Fixed issue by adding a new check in the daily plan edit view:
![messagenoattendance](https://cloud.githubusercontent.com/assets/4991526/13378365/65576b0e-de04-11e5-8f07-75a33fe164c1.png)

Added wheelchair information as a text (end of third line):
![messagewheelchair](https://cloud.githubusercontent.com/assets/4991526/13378370/92f71bc2-de04-11e5-895c-dbbaf317cb0d.png)

Dependancy:
This should also be checked in the optimization class, such driver / customer pairs should not be build automatically.
