### ISSUE TITLE
Einsatzplan bereitstellen -> Fehlermeldung!

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#162]
Produktionsplan -> Februar -> März -> April erstellt.
Wenn Einsatzplan für Monat März heruntergeladen wird, erscheint Fehlermeldung (siehe Snapshot).

![einsatzplan laden](https://cloud.githubusercontent.com/assets/7513352/13078011/caf370e4-d4bc-11e5-8fa0-214ef7e11639.PNG)

Bei Februar und April kein Problem!

**Comment by Martin-Jonasse** [comment]
Fixed issue. wkhtmltopdf crashes with filenames containing an umlaut (like in März).
