### ISSUE TITLE
Fehlermeldung im PDF File "Frühschicht Aftrag drucken"!

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#165]
![fruhschicht drucken](https://cloud.githubusercontent.com/assets/7513352/13570175/eda4902c-e46c-11e5-8800-47f4238a195a.PNG)

**Comment by Martin-Jonasse** [comment]
Fixed, using php->iconv and ISO-8859-1//TRANSLIT.
P.S. ASCII//TRANSLIT doesn't work, it adds whitespace.
