### ISSUE TITLE
Produktionsplan Error

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#168]
- Frühschicht angelegt
- Fahrgast mit Frühschicht angelegt
- Fahrer mit Frühschicht angelegt
- Fahrer ist korrekt im Monatsplan angelegt worden
- ein Fahrzeug für Frühschicht angelegt
- Fahrzeug erscheint nicht im Monatsplan
- 20 Fahrzeuge angelegt
- Fahrzeuge erscheinen im Monatsplan (snapshot-5)
![snapshot-5](https://cloud.githubusercontent.com/assets/7513352/13702645/66d54b28-e790-11e5-8acd-19401b355589.PNG)
- Fahrgast & Fahrer sind zugewiesen -> trotzdem Fehlermeldung (siehe Snapshot-6)
![snapshot-6](https://cloud.githubusercontent.com/assets/7513352/13702699/be48ffda-e790-11e5-9c47-507cba70530f.PNG)
- Fahrer & Fahrgast für Frühschicht gelöscht 
- Frühschicht löschen -> (siehe Snapshot-7)
![snapshot-7](https://cloud.githubusercontent.com/assets/7513352/13702844/c40db4dc-e791-11e5-8796-f3a38ab7d960.PNG)

**Comment by Martin-Jonasse** [comment]
This is not an error, you forgot to allocate (drag+drop) the drivers and
![66d54b28-e790-11e5-8acd-19401b355589](https://cloud.githubusercontent.com/assets/4991526/13704655/41e77db0-e79d-11e5-942e-0861b8b7f3de.PNG)
 vehicles to the pools:

**Comment by Martin-Jonasse** [comment]
Added some code for adding driving pools and allocating vehicles (as desired):
![fruehschicht20](https://cloud.githubusercontent.com/assets/4991526/13722894/67411136-e854-11e5-9436-8555d1b3a233.png)
