### ISSUE TITLE
Improve security for ROLE_DISPO

### ISSUE THREAD

**Issue by Martin-Jonasse** [hertus/sfitixi#192]
Only support and manager related functions are "secured" using the following statements:

if (false === $this->get('security.context')->isGranted('ROLE_MANAGER')) {
            throw new AccessDeniedException();
}

Extend this to all other requests using ROLE_DISPO.

**Comment by faustos** [comment]
This is not necessary because all routes are secured with "is_authenticated_fully". This enforces the user to be autheticated with ROLE_DISPO at least. Only roles with higher hierarchy needs to be checked explicitly. The setting can be found in app/config/security.yml

**Comment by Martin-Jonasse** [comment]
faustos: This is not necessary because all routes are secured with "is_authenticated_fully". This enforces the user to be autheticated with ROLE_DISPO at least. Only roles with higher hierarchy needs to be checked explicitly. The setting can be found in app/config/security.yml

**Comment by Martin-Jonasse** [comment]
Carmelo

Thanks. I’ve closed the issue.

Kind regards, Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 25.06.2016 um 09:41 schrieb faustos <notifications@github.com>:
