### ISSUE TITLE
drivingOrder change process

### ISSUE THREAD

**Issue by hertus** [hertus/sfitixi#57]
no change process implemented, like in drivingPool/drivingAssertion. This includes: Creation of drivingMission per drivingOrder and if any amount or time changes, esspecially in a repeatedDrivingOrder, all responsible drivingOrder objects have to change, dayPlan have to change etc.

**Comment by Martin-Jonasse** [comment]
Fixed (22.05.2015) a large part of this issue in the "driving order" and "repeated driving order" processes/workflows. Missing are the changes of working months, which will be managed in the dispo process. 
A set of use cases has been defined in order to keep a clean set of targets.
