### ISSUE TITLE
Fahrgast -> Abwesenheiten -> Löschen

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#62]
Fehlerbeschreibung:
Bei einem Abwesenheits-Eintrag, der gelöscht werden soll, wird keine Bestätigung eingeholt.
Bei mehreren Einträgen jedoch, wird nach jedem Löschen eine Bestätigung eingeholt.

Erwartung: Jeder Löschvorgang muss mit einer Bestätigung abgeschlossen werden.

![abwesenheit-lschen](https://cloud.githubusercontent.com/assets/7513352/3569812/b2659f30-0b45-11e4-84da-fcdc08b3e5e7.PNG)

![abwesenheit-lschen-2](https://cloud.githubusercontent.com/assets/7513352/3569619/3de1765a-0b42-11e4-9c72-2509eb524dc7.PNG)

![abwesenheit-lschen-3](https://cloud.githubusercontent.com/assets/7513352/3569751/6460c63a-0b44-11e4-9d8c-6be25179f141.PNG)

**Comment by Martin-Jonasse** [comment]
This issue is rejected, absences have been posptponed to a future release. This is to simplify change management.
