### ISSUE TITLE
Neue OVI-adresse-erfassen!

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#65]
Neue OVI Adresse erfassen -> Fehler!
- neue OVI-Adresse -> wird erfasst -> gespeichert -> 
![ovi-erfassen-1](https://cloud.githubusercontent.com/assets/7513352/3643436/591c54ee-10d3-11e4-8a61-b3e801d11f71.PNG)

Resultat nach speichern!
- leere Felder für Adressangaben werden angezeigt
- trotz erfasster Adresse werden Google-Koordinaten nicht angezeigt
![ovi-erfassen](https://cloud.githubusercontent.com/assets/7513352/3642964/5263a0ec-10cb-11e4-9944-b106168c7465.PNG)

Resultat nach doppelklick auf leeres Koordinaten-Feld!
- Google-Adresse zeigt nach Belgien
![ovi-erfassen-3](https://cloud.githubusercontent.com/assets/7513352/3643512/77edaac0-10d4-11e4-979a-8b7b20673157.PNG)

Erwartet wird eine vollstndige Adresse mit:
- allen Eingabe-Feldern und den neu erfassten Angaben
- Google-Coordinaten müssen automatisch abgefüllt werden
- es wurden instabiele Resultate festgestellt

**Comment by Martin-Jonasse** [comment]
Fixed the google interface to display preferably addresses in a "google viewport" (customer N, S, E, W boundery) and filter things such that only swiss, german, austrian and french addresses are displyed.
See defnitions in tixi.yml.
