### ISSUE TITLE
Verwaltung -> Alle Fahrzeugdepots -> Neues Fahrzeugdepot -> Edit Error SOX!  

### ISSUE THREAD

**Issue by Josi-Conrad** [hertus/sfitixi#98]
Ein neues Depot wird angelegt, gespeichert und danach gelöscht, soweit i.O (siehe Snapshot) 

![fahrzeugdepot-2](https://cloud.githubusercontent.com/assets/7513352/3887528/22c2e00e-21f2-11e4-91f9-93a7110f1a28.PNG)

![fahrzeugdepot-1-1](https://cloud.githubusercontent.com/assets/7513352/3887545/89f705a2-21f2-11e4-8f4d-af48aadedaaa.PNG)

Gleiches Depot kann nochmals erfasst und editiert werden!
Erwartet wird, dass nicht mehr editiert werden kann, -> SOX (siehe Snapshot)!

![fahrzeugdepot-3](https://cloud.githubusercontent.com/assets/7513352/3887590/94773dac-21f3-11e4-92a5-1fa65cde423e.PNG)
 
.

**Comment by Martin-Jonasse** [comment]
Implemented (long ago), the option "alle anzeigen" has been disabled as posing a risk to the application.
